FROM python:3.8.10
FROM mysql:5.7
WORKDIR /test
COPY ./tests/test.sql /docker-entrypoint-initdb.d/
ENV DB_PASSWORD=${DB_PASSWORD}, MYSQL_DATABASE=test
RUN pip3 install -r requirements.txt
ENTRYPOINT pytest -m 'models'