FROM mysql:5.7
# Use a base image that includes Python
FROM python:3.8.10

# Set the working directory
WORKDIR /test

# Copy your test SQL script
COPY ./tests/test.sql /docker-entrypoint-initdb.d/

ENV DB_PASSWORD=${DB_PASSWORD}, MYSQL_DATABASE=test
# Install any Python dependencies you need
COPY requirements.txt .
RUN pip install -r requirements.txt

# Specify the command to run your tests

ENTRYPOINT pytest --cov