# Derived from official mysql image (our base image)
# Use mysql 5.7 as the flask-app is not set up to work with later versions
FROM mysql:5.7
FROM python:3.8.10
WORKDIR /app
COPY . .
RUN pip3 install -r requirements.txt
ENV MYSQL_DATABASE cinema
COPY ./db/db.sql /docker-entrypoint-initdb.d/
ENTRYPOINT python3 create.py
